/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData star_empty = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData pinterest_squared = const IconData(0xf0d3, fontFamily: _kFontFam);
  static const IconData gplus_squared = const IconData(0xf0d4, fontFamily: _kFontFam);
  static const IconData gplus = const IconData(0xf0d5, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData thumbs_up_alt = const IconData(0xf164, fontFamily: _kFontFam);
  static const IconData thumbs_down_alt = const IconData(0xf165, fontFamily: _kFontFam);
  static const IconData youtube_squared = const IconData(0xf166, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xf167, fontFamily: _kFontFam);
  static const IconData youtube_play = const IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData tumblr = const IconData(0xf173, fontFamily: _kFontFam);
  static const IconData tumblr_squared = const IconData(0xf174, fontFamily: _kFontFam);
  static const IconData pinterest = const IconData(0xf231, fontFamily: _kFontFam);
  static const IconData twitter_squared = const IconData(0xf304, fontFamily: _kFontFam);
  static const IconData facebook_squared = const IconData(0xf308, fontFamily: _kFontFam);
  static const IconData linkedin_squared = const IconData(0xf30c, fontFamily: _kFontFam);
}
